### ISSUE TITLE
Binary feature rollouts without user id always return false

### ISSUE THREAD

**Issue by FelipeLahti** [optimizely/javascript-sdk#132]
`optimizely.isFeatureEnabled('flagkey')` always return `false` when a userId isn't provided.

Would be cool if the userId isn't required. Sometimes you don't care about rollout percentages and you just want it on or off for all users so passing a user-id would be meaningless.

Thoughts?

**Comment by tylerbrandt** [comment]
Hi @FelipeLahti,

Thanks for the suggestion! We'll take it under consideration and get back to you.

**Comment by spencerwilson-optimizely** [comment]
Hi @FelipeLahti ,

We just discussed this proposal, and decided we won't be making this change in the foreseeable future.

First, there's a workaround: using any non-empty string as the `userId`:
```js
const enabled = optimizely.isFeatureEnabled('foo', 'flagkey', {});
```
If such "binary rollouts" (0% or 100%) are a common pattern in your organization, you could make a helper like
```js
// Also could be called `isBinaryRolloutEnabled`, or something
function anonymousIsFeatureEnabled(featureKey) {
  return optimizely.isFeatureEnabled('unused', featureKey, {});
}
```

Also keep in mind that if you're running an A/B test or feature test (rather than a rollout), in which case you probably _do_ care about attribution and would want to use meaningful ids anyway.

We're wary to add complexity like optional non-last positional arguments. Thanks for giving the feedback and if you have any follow-up comments or questions, or new arguments in favor of this proposal, then please let us know here. Cheers!

**Comment by FelipeLahti** [comment]
If the api was something like:
```javascript
const enabled = optimizely.isFeatureEnabled('flagKey', 'userId');
```
 That suggestion might have been easier and would not be a breaking change. I have been using any `userId` as an workaround as you suggested. Thanks for looking into that.

**Comment by FelipeLahti** [comment]
It would be good to have a default value for `userId` that is handled by the API. 
As an suggestion, I would use an UUID as default when no userId is provided or at least an warning/error.

As an workaround, I basically encapsulated the call to it and I check if `userId` was defined before sending it.

```javascript
// https://github.com/optimizely/javascript-sdk/issues/132
function getUserId(userId) {
  return userId === undefined ? 'userId' : userId;
}

// https://github.com/optimizely/javascript-sdk/issues/146
function getUserAttributes(userAttributes) {
  if (userAttributes) {
    const userAtributtesStringify = {};
    Object.keys(userAttributes).forEach((key) => {
      if (userAttributes[key] !== undefined) {
        userAtributtesStringify[key] = userAttributes[key].toString();
      }
    });
    return userAtributtesStringify;
  }
  return userAttributes;
}

function isFeatureEnabled(flagKey, userId, audiences) {
  return optimizely.isFeatureEnabled(flagKey, getUserId(userId), getUserAttributes(audiences));
}
```
