### ISSUE TITLE
Users are able to be bucketed into multiple variants

### ISSUE THREAD

**Issue by DDChiang** [optimizely/javascript-sdk#145]
When changing allocations between variations in my Optimizely dashboard, my users were able to be bucketed into multiple variants. I assumed that once a user gets bucketed into a variation, they stay in that bucket (this works as expected in the web app when using Optimizely X FullStack project with ruby). But with the React Native app, which uses this library (which points to the same project), this is seeming to not be the case. 

Is this expected? Am I doing something wrong?

In my js app, I'm calling the `activate` method on  `optimizelyClientInstance`. 

**Code:**

Create Optimizely Client using project datafile that's been fetched
```
optimizelyClientInstance = optimizely.createInstance({
  datafile: newDatafile,
});
```

Later, I'm checking variations my 3 users are assigned to.
```
const variation = optimizelyClientInstance.activate(
  experimentName,
  9255,
  attributes,
);

const var2 = optimizelyClientInstance.activate(
  experimentName,
  'aa',
  attributes,
);

const var3 = optimizelyClientInstance.activate(
  experimentName,
  'bb',
  attributes,
);
```

**Screenshots** of variants per user when I was changing allocations: https://screencast.com/t/0rOfarGaC

**Comment by mikeng13** [comment]
@DDChiang this is the expected behavior of the SDK since it is mostly stateless and does not persist previous variation assignments. In order to persist variation assignments you'll have to implement and provide a [UserProfileService](https://developers.optimizely.com/x/solutions/sdks/reference/?language=javascript#profiles). " 

Please refer to this Knowledge Base article for more information: https://help.optimizely.com/Build_Campaigns_and_Experiments/How_bucketing_works_in_Optimizely's_Full_Stack_SDKs#Ensure_consistent_visitor_bucketing
